name: CI/CD on actions for automated project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

job:
   build-and-test:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code repository
         uses: actions/checkout@v3

       - name: Set up python 3.9
         uses: actions/setup-python@v4
         with:
           python-version: 3.9

       - name: install required dependencies
         run: |
           python -m pip install --upgrade pip
           pip install flask
           pip install pytest

       - name: Run the tests using pytest
         run: |
           pytest

   build-and-publish:
     needs: build-and-test
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code repository
         uses: actions/checkout@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2

       - name: Login to DockerHub using Credentials
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Build the Docker image and Push it on DockerHub
         uses: docker/build-push-action@v4
         with:
           context: .
           file: ./dockerfile
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/flasktest-app:latest

       - name: Image Digest to output
         run: echo ${{ steps.docker_build.outputs.digest }}